notifications:
    - provider: Email
      on_build_success: false

clone_folder: c:\projects\okhttp-fork
clone_script:
    - git config --global core.autocrlf input
    - git clone --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

shallow_clone: true

build:
    parallel: true

platform:
    - x86
    - x64

image:
    - Visual Studio 2017
    - Visual Studio 2015

configuration:
    - Debug
    - Release

environment:
    matrix:
        - SHARED: OFF
        - SHARED: ON

matrix:
    fast_finish: false
    allow_failures:
        - SHARED: ON

build_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_SHARED_LIBS=%SHARED% -DENABLE_DTLS=ON -DBUILD_TESTING=ON
    - cmake --build .
