notifications:
    - provider: Email
      on_build_success: false

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\okhttp-fork
shallow_clone: true

build:
    parallel: true

environment:
    OPENSSL_ROOT_DIR: C:\OpenSSL-Win64
    matrix:
        - SHARED: ON
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - SHARED: ON
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        - SHARED: OFF
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - SHARED: OFF
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

matrix:
    fast_finish: false
    allow_failures:
        - SHARED: ON

configuration:
    - Debug
    - Release

install:
    - git submodule update --init --recursive

build_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_SHARED_LIBS=%SHARED% -DDTLS=ON
    - cmake --build .
