dist: trusty
sudo: required

notifications:
    email:
        on_success: never
        on_failure: always

language: cpp
cache: ccache

os:
    - linux

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages: ["g++-5"]

matrix:
    include:
        # Tester and reporter
        - compiler: gcc
          env: BUILD_TYPE=Debug SHARED=ON TESTS=ON
          addons:
              apt:
                  sources:
                      - sourceline: 'ppa:ubuntu-toolchain-r/test'
                  packages:
                      - g++-5
                      - lcov
          script:
              - cmake .. -DCOVERAGE=ON -DTESTS=$TESTS -DCMAKE_BUILD_TYPE=$BUILD_TYPE
              - sudo make -j4
              - make coveralls
              - lcov -c -d . -o coverage.info
              - lcov -r coverage.info "/usr/*" "$TRAVIS_BUILD_DIR/tests/*" -o coverage.info
              - bash <(curl -s https://codecov.io/bash)

env:
    global:
        - TESTS=OFF
    matrix:
        - BUILD_TYPE=Debug SHARED=ON
        - BUILD_TYPE=Debug SHARED=OFF
        - BUILD_TYPE=Release SHARED=ON
        - BUILD_TYPE=Release SHARED=OFF

before_script:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
    - mkdir build
    - cd build

script:
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=$SHARED -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DTESTS=$TESTS
    - sudo make install -j4
