dist: trusty
sudo: required

notifications:
    email:
        on_success: never
        on_failure: always

language: cpp
cache: ccache

os:
    - linux

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages: ["g++-5"]

matrix:
    include:
        # Tester
        - compiler: clang
          env: BUILD_TYPE=Debug SHARED=ON TESTS=ON
          after_script:
              - make test
        # Samples compiler
        - compiler: clang
          env: BUILD_TYPE=Release SHARED=ON SAMPLES=ON

env:
    global:
        - TESTS=OFF
        - SAMPLES=OFF
    matrix:
        - BUILD_TYPE=Debug SHARED=ON
        - BUILD_TYPE=Debug SHARED=OFF
        - BUILD_TYPE=Release SHARED=ON
        - BUILD_TYPE=Release SHARED=OFF

before_script:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
    - mkdir build
    - cd build

script:
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=$SHARED -DTESTS=$TESTS -DSAMPLES=$SAMPLES -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - sudo make install -j4
